"""
Django settings for todoapi project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")
DEBUG = config("DEBUG", cast=bool, default=False)
ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv(), default="127.0.0.1,localhost")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",

    # Local
    "accounts",
    "tasks",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'todoapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'todoapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = "accounts.User"


# ------------------------------------------------------------------
# Django REST Framework configuration
# ------------------------------------------------------------------
REST_FRAMEWORK = {
    # Which authentication backends DRF tries, in order. JWT first means
    # `Authorization: Bearer <token>` headers are honored. Session auth is
    # kept so we can use the browsable API and admin while logged in.
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),

    # Global default permission. Individual views can override this.
    # Default to "authenticated" so we fail closed — new endpoints are
    # private unless we explicitly open them.
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}


# ------------------------------------------------------------------
# SimpleJWT configuration
# ------------------------------------------------------------------
from datetime import timedelta  # noqa: E402  (imports belong at top normally,
                                 # but grouping it here keeps the JWT config self-contained)

SIMPLE_JWT = {
    # Short-lived access token. If this leaks, the blast radius is 30 min.
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),

    # Long-lived refresh token. Used only to mint new access tokens.
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),

    # Every time the client refreshes, issue a NEW refresh token and
    # invalidate the old one. This makes stolen refresh tokens useless
    # after the legitimate user refreshes.
    "ROTATE_REFRESH_TOKENS": True,

    # When rotating, also blacklist the old refresh token so it can never
    # be used again. Requires the `token_blacklist` app in INSTALLED_APPS.
    "BLACKLIST_AFTER_ROTATION": True,

    # Update the user's last_login field on successful token obtain.
    "UPDATE_LAST_LOGIN": True,

    # Where to find the token in the request. Standard is "Bearer".
    "AUTH_HEADER_TYPES": ("Bearer",),

    # Claim names — we keep the defaults so we don't confuse ourselves.
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}